### ISSUE TITLE
Trouble when reading ascii RAW file after AC analysis

### ISSUE THREAD

**Issue by aoki-works** [DongHoonPark/ltspice_pytool#11]
Hi. I'm using your lib. 
There is a problem reading the ascii RAW file after AC analysis.
LTSPICE may add a tab character after the comma(,), as shown below.

```
Values:
0		1.000000000000000e-001,	0.000000000000000e+000
	0.000000000000000e+000,0.000000000000000e+000
	1.000000000000000e+000,0.000000000000000e+000
```

In this case, ltspice_pytool cannot read the real part. To avoid this problem, I'm  using your code with the following modification:

`[line 192]
complex(*[float(y) for y in x.replace('\t,',',').replace(',\t',',').split('\t')`

I hope this issue will be officially resolved. 
best regards,
Aoki

**Comment by donghoonpark** [comment]
Thank you for your detailed bug report.
The point you mentioned was not the case that I tested, which is ascii AC. 
So, I've added the test case in unit test and changed code in the [10f62bf](https://github.com/DongHoonPark/ltspice_pytool/commit/10f62bf2d34ae4fec9f6f2194b48c35f61b9f7ae).
Code revision is little bit different from the one that you've suggested.
You can also download new 1.0.1 version on pip.
Regards.
