### ISSUE TITLE
I have a problem with a .tran simulation rawfile, error raise FileSizeNotMatchException  ltspice.FileSizeNotMatchException ’

### ISSUE THREAD

**Issue by Wallflower123** [DongHoonPark/ltspice_pytool#15]
I have used the ltspice library recently to read rawfiles of both .tran and .ac simulation of the NgSpice simulator.
However, when it comes to this particular [one](https://drive.google.com/file/d/1W2zNAL5Iw6O-n9_yn6_to7VmtB1gT9W8/view), I get error  `raise FileSizeNotMatchException ltspice.FileSizeNotMatchException`.

I'm thinking maybe because it is voluminous(?)

Any ideas how to solve it? 

Thanks in advance

**Comment by donghoonpark** [comment]
Your .raw file uses a double-precision data type. 
So, you need to specify it before parsing.

```python
from ltspice import Ltspice

l = Ltspice("your-raw-file.raw").set_variable_dtype(float)
l.parse()
```

I think it would be better to make a more specific exception type such as DoublePrecisionDtypeRequriedException (it may too long..) to easily debug this kind of human error.
If you have any great idea, please mention it in this thread.

Regards.

**Comment by Wallflower123** [comment]
Have you tried it on the file I shared? 
Because I still get the same error unfortunately ...

**Comment by donghoonpark** [comment]
Yes, I did. I tried with the .raw file you have given which is a size 1.23GB. You'd better check the library version or code.

Regards.

**Comment by Wallflower123** [comment]
You are right, I confused the libraries, how stupid of me!

Thank you so much for your time, your precious help and, guidance!
