### ISSUE TITLE
02 - Multi point simulation - Ltspice error - Singular Matrix: Check node cap

### ISSUE THREAD

**Issue by felipjimss** [DongHoonPark/ltspice_pytool#17]
Hi,

I am trying to simulate the Multi point simulation, but when I try to run the Ltpice circuit to generate the log file, it gives me the error

Singular Matrix: Check node cap

Any ideia about this error?

**Comment by donghoonpark** [comment]
It seems like that the error is about LTSpice simulation itself, not this library. 
Regards.
