### ISSUE TITLE
Support for ngspice .raw files?

### ISSUE THREAD

**Issue by hacksterous** [DongHoonPark/ltspice_pytool#18]
Hi,

I am seeing a FileSizeNotMatchException when trying to load a binary raw file output from ngspice.
Does this mean ngspice is not supported?

>>> l.parse()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/ltspice/ltspice.py", line 160, in parse
    raise FileSizeNotMatchException
ltspice.ltspice.FileSizeNotMatchException

**Comment by hacksterous** [comment]
ltspice.Ltspice(f).set_variable_dtype(float) fixes this for ngspice raw files. Closing the bug

**Comment by donghoonpark** [comment]
Thank you for finding solution by yourself 
: )
