### ISSUE TITLE
parsing ngspice .raw files

### ISSUE THREAD

**Issue by MCO-SOCOMEC** [DongHoonPark/ltspice_pytool#20]
Hi,
I'm trying to use lgspice to read a ngspice .raw file but I get a "FileSizeNotMatchException" when I parse it. I found online that even ngspice raw file format should be supported, isn't it?
thanks
Michele

**Comment by donghoonpark** [comment]
You may be using 64b file. 
Please read #18

**Comment by donghoonpark** [comment]
If you cannot resolve issue, please open this issue again.
