### ISSUE TITLE
Error While parsing Raw file

### ISSUE THREAD

**Issue by nataraj-pinakapani** [DongHoonPark/ltspice_pytool#27]
I get the following error while trying to parse the attached raw file. Can you please help me debug this issue?

**Traceback (most recent call last):

  File ~/projects/designmyic/cad/tee-internal/codes/sde/sde.py:22 in <module>
    l.parse() # Data loading sequence. It may take few minutes for huge file.

  File ~/anaconda3/lib/python3.9/site-packages/ltspice/ltspice.py:177 in parse
    raise FileSizeNotMatchException

FileSizeNotMatchException**

FileSizeNotMatchException
[netlist_0.raw.gz](https://github.com/DongHoonPark/ltspice_pytool/files/9693556/netlist_0.raw.gz)

**Comment by donghoonpark** [comment]
It looks like you are using 64bit data type for variables.
Duplicated issue with #15
