### ISSUE TITLE
double precision .raw file

### ISSUE THREAD

**Issue by blubbrezn** [DongHoonPark/ltspice_pytool#7]
hi DongHoonPark,
I really like your package, thanks a lot!
I noticed that it does not parse simulations that are saved with double precision 
If the option NUMDGT = 7 or bigger is used all datapoints are double-precision
-> I fixed this, take a look into my fork https://github.com/blubbrezn/ltspice_pytool
You can use this in your package if you want.
I also noticed that it doesnt work with non-binary .raw files, which isn't necessary but an error message if the keyword binary is not found would be nice.

best regards
blubbrezn

**Comment by donghoonpark** [comment]
I'm really glad to hear that you use this package useful! I'll merge the feature that you implemented on the next commit. And, when it comes to the non-binary .raw file, it would be better to add the feature that can read it.  Thanks for your opinion!
